ALTER TABLE employers
ALTER COLUMN yearly_revenue
SET DATA TYPE FLOAT;

ALTER TABLE users
ALTER COLUMN full_name
SET DATA TYPE VARCHAR(300);

ALTER TABLE conversation
ALTER COLUMN date_sent
SET DEFAULT CURRENT_TIMESTAMP;